name: dev-builds

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'builds/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install
      - run: yarn build

      - name: Publish dev build
        run: .github/scripts/publish-dev-build '${{ secrets.DEV_BUILD_GITHUB_TOKEN }}'